# Placeholder Docker Compose config until i can test the container properly
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://db:27017/todo_Docker
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo-network

  db:
    image: mongo:7.0
    container_name: mongo-todo
    ports:
      - "27017:27017"
    volumes:
      - todo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - todo-network

volumes:
  todo_data:

networks:
  todo-network:
    driver: bridge